# Prolog - Auto Generated #
import os, uuid, matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot
import pandas

import sys
sys.tracebacklimit = 0

os.chdir(u'C:/Users/TEMP/PythonEditorWrapper_4b8e18ee-4db1-4512-a399-13f5854217d1')
dataset = pandas.read_csv('input_df_e0ae3c0a-6719-4b33-b798-c14629961592.csv')

matplotlib.pyplot.figure(figsize=(5.55555555555556,4.16666666666667), dpi=72)
matplotlib.pyplot.show = lambda args=None,kw=None: matplotlib.pyplot.savefig(str(uuid.uuid1()))
# Original Script. Please update your script content here and once completed copy below section back to the original editing window #
##############################

# Epilog - Auto Generated #
os.chdir(u'C:/Users/TEMP/PythonEditorWrapper_4b8e18ee-4db1-4512-a399-13f5854217d1')
